### PR TITLE
Input manager

### LINKED ISSUE #144: Inputs interface for qwerty and gamepad

### PR DESCRIPTION
**Pull request by paulbaron**
Context abstraction (SDL only included in SdlContext.cpp and nowhere else)
Input Abstraction (AGE enums for inputs)
Controller (XboX controller handling)
Difference between mapped and physical keys
It is VERY LONG and laborious to add another context (you need to reimplement the files SdlContext.cpp, SdlContext.hh and SdlToAgeInputs.cpp and to add a visual studio configuration to exclude those files from the project and replace them with the new implementation) so the GLFW context might never be implemented (it works very well with the SDL).
close #144

### CODE REVIEW

**Comment by cesarl** [comment]
That'is totaly okay for me ! Great job !!! :clap: 

Juste on question / problem. When the Xbox controller is plugged, we don't have access anymore to keyboards input. It'll be great to have both access.

**Comment by paulbaron** [comment]
Then juste move the block of code that handles the keyboard input outside the "else" statement.

**Comment by cesarl** [comment]
I let you do it on my last PR :)

2015-03-10 9:41 GMT-04:00 paulbaron <notifications@github.com>:

> Then juste move the block of code that handles the keyboard input outside
> the "else" statement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/366#issuecomment-78054238>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
I gonna modify 1 or 2 things before merging this

**Comment by cesarl** [comment]
oki ! work on MY PR i merge it with your code and update it with master's
code

2015-03-10 10:20 GMT-04:00 paulbaron <notifications@github.com>:

> I gonna modify 1 or 2 things before merging this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/366#issuecomment-78062465>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by DorianPinaud** [comment]
good for me :D

**Comment by cesarl** [comment]
DO NOT MERGE IT WE HAVE PROBLEM WITH THREADS

**Comment by paulbaron** [comment]
My last commit correct the bug normally... have you tried it?

**Comment by cesarl** [comment]
Not yet. Can you merge it with implement_new_deferred_shading please
(normally i correct it on the branch to)


2015-03-11 6:02 GMT-04:00 paulbaron <notifications@github.com>:

> My last commit correct the bug normally... have you tried it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/366#issuecomment-78234814>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Pull request closed without merging**
