### PR TITLE
Audio documentation

### PR DESCRIPTION
**Pull request by BoucherAnthony**
Technical documentation of the Audio part of the Engine.

### CODE REVIEW

**Comment by DorianPinaud** [comment]
good for me

**Comment by cesarl** [comment]
Okay for me :confetti_ball:

**Comment by cesarl** [comment]
Heuuu @BoucherAnthony why is it on .dox file and not in .cpp file from which we generate the documentation ? It's useless in .dox file uniquely, if we change sources, docmentation will not follow

**Comment by DorianPinaud** [comment]
it is a decision of laureline and antho. personnaly I prefere that I don't like when the code is mixed with commentaries ^^

**Comment by cesarl** [comment]
I do notre agree with that idea because the code will change a lot and
documentation will be deprecated very fast. But as the majority wants :)

Le mer. 14 janv. 2015 14:30, DorianPinaud <notifications@github.com> a
écrit :

**Comment by paulbaron** [comment]
I vote for documentation in .cpp file too:
As Cesar says, the .dox will be outdated very quickly without anyone noticing and having the doc in the .cpp allow an integration in visual studio (autocompletion).

**Comment by BoucherAnthony** [comment]
I don't mind, I started on .hpp files but it makes file much more heavier and less readable.
The problem, is as you say no one will keep up to date the documentation if they have to switch mind.

**Comment by cesarl** [comment]
the file will not be so heavy, we can collapse them on visual studio,
search about collapsing code section on google about, you can do a lot with
that :)

2015-01-16 11:25 GMT-05:00 BoucherAnthony <notifications@github.com>:

> I don't mind, I started on .hpp files but it makes file much more heavier
> and less readable.
> The problem, is as you say no one will keep up to date the documentation
> if they have to switch mind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/297#issuecomment-70279097>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by BoucherAnthony** [comment]
As you wish I don't care, juste find an agreement between you ^^

**Comment by cesarl** [comment]
Mets les dans le code dans des blocks : `pragma region documentation` ... `pragma endregion documentation`

http://msdn.microsoft.com/en-us/library/b6xkz944.aspx

**Comment by cesarl** [comment]
@BoucherAnthony Mets les dans le code dans des blocks : `pragma region documentation` ... `pragma endregion documentation`

http://msdn.microsoft.com/en-us/library/b6xkz944.aspx

**Comment by BoucherAnthony** [comment]
@cesarl  Au dessus de chaque fonction, ou au dessus/dessous de la classe je refais une classe mais pour la doc ?

**Pull request closed without merging**
