### PR TITLE
IcoSphere generation integrated to RenderThread

### LINKED ISSUE #351: Icosphere

### PR DESCRIPTION
**Pull request by paulbaron**
Icospheres integrated (not tested yet, but should work as the code is simply a copy/paste from an old commit)
close #351

### CODE REVIEW

**Comment by cesarl** [comment]
You renamed "ComponentRegistrar" into "RegisterComponent"
That singleton is responsible of registering component type. So it's a _registrar_ who _register_ stuff.
Registrar in french : greffier, chef du service des inscriptions

Can you put back the old name please :)

**Comment by paulbaron** [comment]
In this context the name is really weird... but wtv ^^
I know it just a detail and we dont want to lose time on that but let's cut the pear in two (very good litteral translation ;) ) and call it "ComponentRegistrationManager"? Sorry for insisting on changing the name but i've seen that few month ago and it really bother me xD

**Comment by paulbaron** [comment]
Ok, you might be right actually, I saw some codes with classes named like that... I surrender :(

**Comment by cesarl** [comment]
Hahaha ! As you want but RegisterComponent is not a good name, it's an action not a name :) If you want to rename it `ComponentRegistrationManager` go for it, i dont care if it express the role of the class correctly :smile:

**Comment by cesarl** [comment]
Great job ! It'll requiere future developments, but for now that really great !

**Pull request merged**
