### PR TITLE
Deffered pass 1 and render to screen

### LINKED ISSUE #357: Init() method for render buffers

### LINKED ISSUE #373: Random behaviour at assets loading
There is a random behaviour when assets are loading in release
Sometime it block at : 2 more assets to load.
And block forever.
We need to search why and fix it ASAP !!!
@paulbaron @DorianPinaud @herpec-j I'll need your help and active participation on that !
Thx :kiss:

### PR DESCRIPTION
**Pull request by cesarl**
Some pipeline bug fix and additions.
Render texture to screen.
Merge with #366

Fix thread bug

Close #373
Close #366
Close #357

### CODE REVIEW

**Comment by DorianPinaud** [comment]
youhou !

**Comment by cesarl** [comment]
D ONOT MERGE IT WE HAVE PROBLEM WITH THREADS

**Comment by paulbaron** [comment]
The performances are terrible on my computer... Is this normal? (It goes up to 20ms per frame for the render thread)

**Comment by cesarl** [comment]
Maybe you are on your chipset
Maybe you are rendering the 2 pipelines at the same time
Maybe it's due to my hardcoded stuff for animations
I'll check that at home this afternoon. But I'm pretty sure that you still
can work with 40 fps


2015-03-11 13:27 GMT-04:00 paulbaron <notifications@github.com>:

> The performances are terrible on my computer... Is this normal? (It goes
> up to 20ms per frame for the render thread)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78312388>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
-I'm on my nvidia GPU without vsync
-I only render the deferred pipeline
-It doesn't stop me from working (60fps in he worst case in debug with visual, but it still pretty lame without lights ^^)
What are the performances on your laptops?

**Comment by cesarl** [comment]
^^
I try that after work and tell you :)
I'm currently watching at nvidia conferences ... soon I'll boost the
pipeline :D :D :D

2015-03-11 13:53 GMT-04:00 paulbaron <notifications@github.com>:

> -I'm on my nvidia GPU without vsync
> -I only render the deferred pipeline
> -It doesn't stop me from working (60fps in he worst case in debug with
> visual, but it still pretty lame without lights ^^)
> What are the performances on your laptops?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78318720>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
Ahah! Cool!
I would say that 5ms would be an acceptable performance for just rendering the deferred buffers.
Let's try to reach that! We need some objectives and motivation ;)

**Comment by cesarl** [comment]
Yes ! :D
But don't forget that priority is feature adn bug fix ! Benchmarking and
optimisation will come after ;)

2015-03-11 14:12 GMT-04:00 paulbaron <notifications@github.com>:

> Ahah! Cool!
> I would say that 5ms would be an acceptable performance for just rendering
> the deferred buffers.
> Let's try to reach that! We need some objectives and motivation ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78332328>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
Sure, but the lightning pass is gonna be very heavy (at least twice the time of the buffering pass) so we need some margin to keep acceptable performances (not like in the first version of the engine where we needed a super-computer to render a frame xD)
But as you want, it doesn't bother me that much ^^.

**Comment by cesarl** [comment]
Hahaha ! Of course we will benchmark regulary and search for improvements
but, we don't have to focus on that. We don't have light and shadow since
more than one year now ! It's a shame ! hahaha.
Do not worry, I'm still the terrible guardian of performances, I'll not let
the past situation repeat another time :D

2015-03-11 14:19 GMT-04:00 paulbaron <notifications@github.com>:

> Sure, but the lightning pass is gonna be very heavy (at least twice the
> time of the buffering pass) so we need some margin to keep acceptable
> performances (not like in the first version of the engine where we needed a
> super-computer to render a frame xD)
> But as you want, it doesn't bother me that much ^^.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78336492>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by cesarl** [comment]
@paulbaron in debug at scene launch without moving the camera I have
between 200 and 350 fps :)

2015-03-11 14:26 GMT-04:00 César Leblic <cesar.leblic@gmail.com>:

> Hahaha ! Of course we will benchmark regulary and search for improvements
> but, we don't have to focus on that. We don't have light and shadow since
> more than one year now ! It's a shame ! hahaha.
> Do not worry, I'm still the terrible guardian of performances, I'll not
> let the past situation repeat another time :D
>
> 2015-03-11 14:19 GMT-04:00 paulbaron <notifications@github.com>:
>
>> Sure, but the lightning pass is gonna be very heavy (at least twice the
>> time of the buffering pass) so we need some margin to keep acceptable
>> performances (not like in the first version of the engine where we needed a
>> super-computer to render a frame xD)
>> But as you want, it doesn't bother me that much ^^.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78336492>
>> .
>>
>
>
>
> --
> [image: dancing frog animation][image: dancing frog animation][image:
> dancing frog animation][image: dancing frog animation][image: dancing
> frog animation][image: dancing frog animation][image: dancing frog
> animation][image: dancing frog animation][image: dancing frog animation][image:
> dancing frog animation][image: dancing frog animation][image: dancing
> frog animation][image: dancing frog animation][image: dancing frog
> animation]
>
>


-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
Yes but i'm talking about worst case, when you draw all sponza. The frame rate should not change that much...

**Comment by cesarl** [comment]
All scene from the top in release : 210 fps

2015-03-11 17:36 GMT-04:00 paulbaron <notifications@github.com>:

> Yes but i'm talking about worst case, when you draw all sponza. The frame
> rate should not change that much...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/pull/367#issuecomment-78377729>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
ok, not that bad ^^

**Pull request merged**
