### PR TITLE
Hard shadow

### LINKED ISSUE #427: Spot light shadow
Shadow pass on spot lights

### LINKED ISSUE #440: hard shadow

### PR DESCRIPTION
**Pull request by DorianPinaud**
hard shadow finish !

close #427 
close #440

### CODE REVIEW

**Comment by paulbaron** [comment]
Good for me!

**Comment by cesarl** [comment]
Super cool and good performance (release)

__BUT__ occlusion scene crash in the editor.

**Comment by DorianPinaud** [comment]
strange, it works on my computer :/

**Comment by DorianPinaud** [comment]
I let you merge it when you will resolve your occlusion scene crash

**Pull request closed without merging**
